
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include groups.yaml


utility_meter:
  linky_daily:
    source: sensor.linky_17175976828544_consumption_standard
    cycle: daily
  linky_weekly:
    source: sensor.linky_17175976828544_consumption_standard
    cycle: weekly
  linky_monthly:
    source: sensor.linky_17175976828544_consumption_standard
    cycle: monthly
  linky_yearly:
    source: sensor.linky_17175976828544_consumption_standard
    cycle: yearly
